### ISSUE TITLE
Tooltip icon color

### ISSUE THREAD

**Issue by ebQWlN5HBDsKVbhnsd5QJMZRshJUyuFm8U3OEwL** [carbon-design-system/carbon-react-native#114]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Tooltip. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-7393&t=pExk7dwH4TEEmGNT-4

Icon should be black when the content is open and visible
<img width="364" alt="tooltip-color" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/0dcbe50a-d69d-4cd4-b440-319801216b9c">

Icon should be greyed out a bit when content is closed and non visible
<img width="1079" alt="visible-non-visible" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/faba3557-0325-47db-890a-02b46303e5fc">

we think the icon is rendering blue from the button style which is influencing the icon color. Design is using an icon but library is using a button, a suggestion from on of our devs: if you could make the trigger a slot that may fix the issue

If you have design questions you can slack `@LISA` or `@rjgervacio`
If you need any additional information you can slack `@kwadwo`

@David-Bradshaw

**Comment by dabrad26** [comment]
Added for iconOnly buttons (which is just the icon version only).

Looked into definition tooltips but iOS does not have support for dashed borders and underlines cannot be colored. Seems small and no requests yet. So will skip for now and if a team needs we can draw the line manually.

https://stackoverflow.com/questions/73506925/when-trying-to-add-a-dashed-border-style-getting-unsupported-dashed-dotted-b

![Screenshot 2023-09-19 at 10 50 41](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/468168a7-43c1-411c-97ef-cd7712ede362)
![Screenshot 2023-09-19 at 10 50 45](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/d36c6b3b-b626-457d-85dc-644eefcf2b40)
