### ISSUE TITLE
Menu updates to match design

### ISSUE THREAD

**Issue by ebQWlN5HBDsKVbhnsd5QJMZRshJUyuFm8U3OEwL** [carbon-design-system/carbon-react-native#115]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Menu. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=12846-269886&t=pExk7dwH4TEEmGNT-4

missing drop shadow around menu box:
<img width="966" alt="menu-dropshadow" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/f53fccbf-5fd8-49e1-81d3-fed6579b8fb1">

can’t put icons to the left right now
<img width="660" alt="menu-item-left-icon" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/3481b373-02c9-42e1-b961-540cfa35ba34">

If you have design questions you can slack `@LISA` or `@rjgervacio`
If you need any additional information you can slack `@kwadwo`

@David-Bradshaw

**Comment by dabrad26** [comment]
Added:
![Screenshot 2023-09-19 at 11 29 35](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/688df9b3-32aa-44f5-a647-13490542ac91)
![Screenshot 2023-09-19 at 11 29 30](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/08132204-b8e4-4368-b1cd-02043343e89f)


To use:

on MenuItem set `icon` to a Carbon Icon.  You can override the color via `iconColor`. If iconColor not set the icon will follow standard rules.

The DropdownItem supports the same props (Dropdown uses Menu under the hood).

maxMenuHeight is now a prop for both Menu and Dropdown.
