### ISSUE TITLE
Toggle updates to match design

### ISSUE THREAD

**Issue by ebQWlN5HBDsKVbhnsd5QJMZRshJUyuFm8U3OEwL** [carbon-design-system/carbon-react-native#117]
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-7275&t=pExk7dwH4TEEmGNT-4

Spacing between value and toggle is different than design (8px) in repo (12px)
<img width="949" alt="toggle-value-spacing" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/a410a340-4bab-41d0-b7ca-bfd4a5fad20b">
Spacing between label and the toggle is different than design 
<img width="703" alt="toggle-label-spaing" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/9f26bf67-7de4-45e0-8435-33797cf63606">
Toggle off state is different than design
<img width="319" alt="toggle-off-state" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/7a190f73-9a16-4e91-9233-7dabf3be65f4">
Toggle disabled state is different than design 
<img width="367" alt="toggle-disabled-state" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924155/5c7d31b7-612a-4d36-b8eb-420e087630a6">

We understand you are migrating toggle to a different implementation so please let us know if any of these will be included in that already planned work. 

If you have design questions you can slack `@LISA` or `@rjgervacio`
If you need any additional information you can slack `@kwadwo`

@David-Bradshaw

**Comment by dabrad26** [comment]
Fixed the padding and sizing.  Correct; we will not adjust the other part of the Toggle as it uses System Toggle (React Native) and we would need to migrate to our own implementation which is a larger undertaking.

![Screenshot 2023-09-19 at 12 03 34](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/b1619d1b-b493-41e6-90be-e29ec9aa640c)
