### ISSUE TITLE
Dropdown updates to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#118]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Dropdown. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=11003-405007&t=pExk7dwH4TEEmGNT-4

- Current dropdown implementation does not have multi-select functionality.
<img width="567" alt="dropdown-multiselect" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/872f64c6-1b64-4860-81d7-1eb97043353a">

- Unable to render icon or checkbox to the left or right of the dropdown item
<img width="251" alt="dropdownitem-lefticon-and-checkbox" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/fe14a591-5a71-41d4-9cb6-7959301942bd">

If you have design questions you can slack @LISA or @rjgervacio
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
Moved to new Ticket as this is a new feature https://github.com/carbon-design-system/carbon-react-native/issues/152
