### ISSUE TITLE
Progress indicator updates to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#119]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Progress indicator. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=12627-270845&t=pExk7dwH4TEEmGNT-4

- The design has an accordion option and a dropdown option - dev library has the accordion but not the dropdown variant.
<img width="263" alt="progressindicator-missing-dropdown" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/af1019e8-b693-4b0e-b2fe-402ffffb9360">

If you have design questions you can slack @LISA or @rjgervacio
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
This can be accomplished using Dropdown with icons and iconColor.  See https://github.com/carbon-design-system/carbon-react-native/issues/115
