### ISSUE TITLE
Text input updates to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#120]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Text input. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-6921&t=pExk7dwH4TEEmGNT-4

- Missing a warning state with warning icon 
<img width="365" alt="textinput-missing-warning" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/eac92e09-2e24-4b61-8e3d-664d7f6a799f">

If there is another way to render this that we are not aware of please let us know.

If you have design questions you can slack @LISA or @rjgervacio
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
Added `warningText` prop which will show warning state when set. If error exists an error takes priority.
![Screenshot 2023-09-19 at 14 00 22](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/2e9590cb-56b2-40c4-968e-7de3e50b5a48)
