### ISSUE TITLE
Pagination dot spacing to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#121]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Pagination. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-5859&t=pExk7dwH4TEEmGNT-4

- The design library is using 8pixels top and bottom padding and 4 pixels left and right padding , while the dev library is currently using  4pixels all around the pagination dot.

![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/2bc091eb-8396-4b3b-a3ff-5320f81e9940)

If you have design questions you can slack @LISA or @rjgervacio
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
Changed to 8 on top and bottom and 4 left and right.
![Screenshot 2023-09-19 at 13 49 19](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/00261a05-c773-44de-8090-0f0d565f7844)
