### ISSUE TITLE
Fullwidth Checkbox active state update

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#122]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Checkbox. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-3970&t=pExk7dwH4TEEmGNT-4

- When you tap on the full width checkbox `<NavigationListItem selectableType=”checkbox”/>` the selected state does not include the checkbox.

<img width="1178" alt="fullwidth-checkbox-active-state" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/395b3d60-53e3-4e85-8bd8-14b7a6acc767">

If there is another way to render this that we are not aware of please let us know.

If you have design questions you can slack @LISA or @rjgervacio
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
Component changed if onPress and onLongPress are not set NavigationList won't show the state change.
