### ISSUE TITLE
Slider textbox updates to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#123]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Slider. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=1880-6449&t=pExk7dwH4TEEmGNT-4

- The text inside the right box is spaced differently than in design spec, would need updates to match designs

<img width="1049" alt="6df19de2-f318-45ba-9667-a45a51a9fe15" src="https://github.com/carbon-design-system/carbon-react-native/assets/8028956/95075faf-d126-4510-b7d6-7dd0d01ac6bf">

If there is another way to render this that we are not aware of please let us know.

**Comment by dabrad26** [comment]
We are not supporting Slider with input on FormItem right now. Only via the Regular Component.  And for that the text matches the size size label is not part of the container.
