### ISSUE TITLE
Notification component needs updates to match design

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#124]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Notification. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(Beta)-Gray-10-Theme-Mobile---Carbon-Design-System?type=design&node-id=1880-5505&t=8njoXVhePM30Alif-4

- The Notification action buttons are missing high contrast variations (Which are to be used with the high contrast Notification component) The Button component allows for color overrides but these overrides do not reflect the active state when the button is pressed down. 
Perhaps the High Contrast variation of the tertiary and ghost buttons could be added to the Button component or perhaps they could be used as built in default action items within the Notification component.

![f2726a18-c0a8-44d3-9422-cd5630e55cb9](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/b9acf1bf-6ec3-4406-94ea-7e75ec31bfb7)

- The notification title and text should not have right margin in order to match with the figma spec

![0aec26a6-7a7f-4c48-8bf3-36ea584418e4](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/8c697b25-39b2-4c2d-aa75-cdede3608ebb)

- The notification component would need a drop shadow to match the figma spec

![3ee3071c-4c81-4c1f-8e27-3b797122d22f](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/c7ba57a7-dac8-4b20-a0c3-2a029b9f1de3)

If there is another way to render these items that we are not aware of please let us know. Thank you

**Comment by dabrad26** [comment]
Button now supports `high-contrast` and `high-contrast-inverse`. These can be used with some extra work

```
<Button forceTheme={lowContrast ? 'light' : undefined} kind={lowContrast ? 'high-contrast' : 'high-contrast-inverse'} style={this.styles.button} onPress={this.actionCallback} text="Action" />
```

This has been added to the documentation for the Notification component. This is needed since Theme manager doesn't handle layers like Notification rendering in light mode in Dark theme with its custom colors.

**Comment by dabrad26** [comment]
Example:

![Untitled5](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/c424cd4d-0301-47da-a89e-732d85d38b4c)

**Comment by dabrad26** [comment]
Drop shadow can be turned on via new prop `dropShadow` (Boolean). This is off by default.
