### ISSUE TITLE
Tablecell section (FormItem type header) design update

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#126]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Tablecell section (Which we call `Formitem type header` in carbon react native library). Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(Beta)-Gray-10-Theme-Mobile---Carbon-Design-System?type=design&node-id=14455-242397&t=9tBXmB1SKwRvXH7Q-4

- Form item type `header` should be 14px rather than 16px in text size
- Form item type `header` description should be 8px of top padding

Library current
![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/aded317b-9429-4f9f-a8d3-1fa04fbfd629)

Figma 
![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/ec75781b-74b2-41a3-915b-054dde577347)

If there is another way to render these items that we are not aware of please let us know. Thank you

If you have design questions you can slack @LISA or @rjgervacio @juanencalada
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
Changed header to `heading-compact-01` and added 4px top padding to header description.

![Screenshot 2023-09-19 at 14 13 20](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/3149ee43-fcb3-451e-88d0-fdb9c16d321d)
