### ISSUE TITLE
Tooltip positioning and updates

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#129]
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Tooltip. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(Beta)-Gray-10-Theme-Mobile---Carbon-Design-System?type=design&node-id=1880-7393&t=8njoXVhePM30Alif-4

- The tool tip component is unable to place content in other positions. Right now the tooltip content will align bottom right of its trigger. But does not have a way of aligning top-right, bottom-left, or top-left. 

Example workaround of desired bottom left aligned content being used in w3 mobile not using the Tooltip component.
![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/164bda48-a65b-4e9d-ba23-cc242686f175)

- Tool tip carets have a configurable size (large and small) in figma spec

Small Caret
<img width="679" alt="small-tooltip-caret" src="https://github.com/carbon-design-system/carbon-react-native/assets/139924156/fd526261-197a-434a-a6ed-265087345aa2">

Large Caret
![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/dbd3405d-4c07-45e7-835f-81905e746f23)

- The tool tip could benefit from having a means of adding a custom trigger (such as an icon for example) in addition to the current built in button and links.

- A prop or means to toggle/manage the tooltip's open and closed status would be helpful.

If there is another way to render or do these things that we are not aware of please let us know. Thank you

If you have design questions you can slack @LISA or @rjgervacio @juanencalada
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment]
As of now not going to support this; will keep this in mind for future plans if we revamp the Tooltip system to support more options.
