### ISSUE TITLE
Beta Gray 10 Theme - Menu component

### ISSUE THREAD

**Issue by OvZwU32sfuriP5Ph8mtbO9kjEXUJUSRhzBelnuz** [carbon-design-system/carbon-react-native#131]
In the Beta Gray 10 Theme Mobile-Carbon Design System Figma file, the "Menu" component needs the divider boolean, full-width option. Design here: https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(Beta)-Gray-10-Theme-Mobile---Carbon-Design-System?type=design&node-id=12846-269886&mode=design&t=RtDwhtY0ecsxTpjy-4

**Comment by dabrad26** [comment]
Added `divider` boolean to MenuItem and DropdownItem.
Full width is already there; it is up to consumer to not wrap it in padding. For our test app all items have wrapping.
![Screenshot 2023-09-19 at 12 25 51](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/c00c9fc1-b361-4a6d-ae26-87d1cf3cb75b)
