### ISSUE TITLE
Beta Gray 10 Theme - Action sheet component

### ISSUE THREAD

**Issue by OvZwU32sfuriP5Ph8mtbO9kjEXUJUSRhzBelnuz** [carbon-design-system/carbon-react-native#132]
In the Beta Gray 10 Theme Mobile-Carbon Design System Figma file, the "Action sheet" component needs the divider boolean, full-width option. Design here: https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(Beta)-Gray-10-Theme-Mobile---Carbon-Design-System?type=design&node-id=12854-270659&mode=design&t=RtDwhtY0ecsxTpjy-4

**Comment by dabrad26** [comment]
Added dividers (for custom); via `divider` param on ActionSheetItems.  `fullBleed` is not a prop for ActionSheet for custom action sheets to not have spacing from edge.
![Screenshot 2023-09-19 at 13 15 35](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/ace62d47-f1e1-4300-8f46-c10841c95acf)
![Screenshot 2023-09-19 at 13 17 35](https://github.com/carbon-design-system/carbon-react-native/assets/8028956/efc67b5b-200c-4600-acd6-6e2732dce45a)
