### ISSUE TITLE
Add `@carbon/telemetry`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-react-native#138]
The `@carbon/telemetry` is a package provided by the core team that is configured to run on a postinstall hook and will report low level anonymous usage data when the package is installed.

In this case it should be a couple simple steps:
```[tasklist]
- [x] Add @carbon/telemetry as a dependency (to ensure it's not dropped by bundlers)
- [x] Invoke it in the `postinstall` script in package.json
```

```json
"scripts": {
    "postinstall": "carbon-telemetry collect --install"
  },
```

**Comment by mattrosno** [comment]
@jdharvey-ibm we'll need to add this package the telemetry back-end after this issue is completed, right?

**Comment by jdharvey-ibm** [comment]
@mattrosno Yep! Actually I think we could add that prior to this issue getting completed. And then we'll add this to our list that needs to be migrated over to the new telemetry collection once we have that ready.

**Comment by jdharvey-ibm** [comment]
Issue to track adding the package to the back-end:

https://github.ibm.com/carbon/ibm/issues/132
