### ISSUE TITLE
Build Release Issues

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon-react-native#150]
@tay1orjones opening this to track this issue.

We are having an issue having the Github Actions to push back to main.  Not sure the setup used in other Carbon repos.  I also tried to add @carbon-bot as an admin.  

Any recommendations on how to make this work?

**Comment by tay1orjones** [comment]
Yes sorry I finally had some time to look into this and put some thoughts into https://github.com/carbon-design-system/carbon-react-native/pull/165

**Comment by tay1orjones** [comment]
Related: https://github.com/release-it/release-it/issues/940

**Comment by tay1orjones** [comment]
I think it's working now after updating the workflow to use a token from carbon-bot and allowing carbon-bot to bypass the branch protections. It still failed, but just due to the package.json not having the correct up to date version https://github.com/carbon-design-system/carbon-react-native/actions/runs/6816422120/job/18537681352

**Comment by tay1orjones** [comment]
I was looking at the wrong workflow run, it still failed https://github.com/carbon-design-system/carbon-react-native/actions/runs/6816767904

I think instead the best approach would be to use an SSH token [like `gatsby-theme-carbon` does](https://github.com/carbon-design-system/gatsby-theme-carbon/blob/37615427c548a64d83acd02091616fb623f50f08/.github/workflows/release.yml#L39C7-L57)

**Comment by dabrad26** [comment]
https://github.com/carbon-design-system/carbon-react-native/actions/runs/6817463537/job/18541019243

Builds are working now! Thanks for the links and issues; we are using SSH connected to my personal account.
