### ISSUE TITLE
Improve security practices for `carbon-react-native`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-react-native#164]
Hey there, Carbon team member here! 👋 We'd like to ensure the security practices for packages published from the `carbon-design-system` GitHub org are in place and up to date. We'd like to work with you to get the following security practices implemented:

```[tasklist]
- [x] Add a security policy to the repository
- [x] Enable Security advisories
- [x] Enable Private vulnerability reporting
- [x] Enable Dependabot alerts
- [x] Enable Code scanning alerts
- [x] Enable Secret scanning alerts
- [x] Publish your package(s) to npm with [provenance statements](https://docs.npmjs.com/generating-provenance-statements)
```

Most of these can be found under the Security tab for this repository. You may already have most of these implemented and turned on - if so, awesome! 

For establishing a security policy, the existing [security policy for the Carbon monorepo](https://github.com/carbon-design-system/carbon/security/policy) can be used as a template if you'd like. It can be modified to include proper version(s) for your package and any other attributes unique to your project that you may want to highlight.

I'm happy to meet up and chat about this if you'd like, just let me know. Thanks in advance for your help in ensuring security and stability across the Carbon ecosystem! 🙏 💙

**Comment by dabrad26** [comment]
All items are added. However, provenance is not yet published.  Currently Github Actions has some issues (see #150 ).  

The other items are complete and I have gone ahead and set the package.json file to provenance; so need to run from GitHub actions to have the standard approach `npm ERR! Automatic provenance generation not supported outside of GitHub Actions`
<img width="1055" alt="Screenshot 2023-11-07 at 01 04 41" src="https://github.com/carbon-design-system/carbon-react-native/assets/8028956/513baf5f-3352-440b-a00f-4cbe41df5794">

@tay1orjones if you have some time could you help me with the GitHub action issue #150?

**Comment by dabrad26** [comment]
Added provenance statement and verified on NPM
<img width="962" alt="Screenshot 2023-11-09 at 13 26 15" src="https://github.com/carbon-design-system/carbon-react-native/assets/8028956/782efd4c-2502-4c1c-bf9e-2ffdad745734">

All items on this ticket are complete; so closing it. Let me know if you need it opened or if something is not right.
